MITE_KEY: 1234567890abcde
MITE_ACCOUNT: mymiteaccount

BUSINESS_DAYS_TO_TRACK: 10

SHOW_GROUPED_BY_DAY: true
SHOW_GROUPED_BY_DAY_AND_ACTIVITY: true
SHOW_FULL_REPORT: false # NOT IMPLEMENTED YET

USERS:
    John: 12345
    Jane: 23456
    Foo: 34567
    Bar: 45678
